name: Terraform Infrastructure Pipeline

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  TF_VERSION: "1.9.8"
  TF_WORKING_DIR: "./module"


# ============================================================
# PR / MAIN - TERRAFORM PLAN
# ============================================================

jobs:

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:

      # ------------------------------------------------------
      # Checkout
      # ------------------------------------------------------

      - name: Checkout Repository
        uses: actions/checkout@v4

      # ------------------------------------------------------
      # Setup Terraform
      # ------------------------------------------------------

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # ------------------------------------------------------
      # Terraform Format
      # ------------------------------------------------------

      - name: Terraform Format Check
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check -recursive

      # ------------------------------------------------------
      # Azure Login using OIDC
      # ------------------------------------------------------

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # ------------------------------------------------------
      # Terraform Init
      # ------------------------------------------------------

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      # ------------------------------------------------------
      # Terraform Validate
      # ------------------------------------------------------

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      # ------------------------------------------------------
      # Terraform Plan
      # ------------------------------------------------------

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan
cd